### ISSUE TITLE
Segfault when viewing charts

### ISSUE THREAD

**Issue by TheJJ** [tomahawk-player/tomahawk#344]
When I click the charts view, i get a segfault:

```
23:03:32 [0]: Tomahawk::ViewPage* ViewManager::showDynamicPage(const QString&) pageName: "charts" 
[New Thread 0x7fff437fd700 (LWP 66330)]
23:03:32 [1]: View page shown: "Charts" 
23:03:32 [1]: Got view page activated for item: "Charts" 
23:03:32 [1]: Got view page activated for index: QModelIndex(2,0,0x1256550,SourcesModel(0x1295600) )  
23:03:32 [1]: void AudioControls::onControlStateChanged() 
23:03:32 [1]: void AudioControls::onControlStateChanged() 
23:03:32 [1]: SpotifyPlugin: InfoChart fetching possible resources 
23:03:32 [1]: virtual void Tomahawk::InfoSystem::SpotifyPlugin::notInCacheSlot(Tomahawk::InfoSystem::InfoStringHash, Tomahawk::InfoSystem::InfoRequestData) fetching:  QUrl( "http://spotikea.tomahawk-player.org/toplist/charts" )  
23:03:32 [1]: void Tomahawk::InfoSystem::SpotifyPlugin::chartTypes() Got spotifychart type result 
23:03:32 [0]: JSonScanner::yylex - unknown char, returning -1 

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc9ff9700 (LWP 66318)]

=> 0x7ffff2e3a2a0 <_ZN8QVariantC2ERKS_>:	mov    eax,DWORD PTR [rsi+0x8]
   0x7ffff2e3a2a3 <_ZN8QVariantC2ERKS_+3>:	mov    edx,DWORD PTR [rdi+0x8]
   0x7ffff2e3a2a6 <_ZN8QVariantC2ERKS_+6>:	mov    rcx,QWORD PTR [rsi]
   0x7ffff2e3a2a9 <_ZN8QVariantC2ERKS_+9>:	and    eax,0x3fffffff
   0x7ffff2e3a2ae <_ZN8QVariantC2ERKS_+14>:	and    edx,0xc0000000

rdi    7fffc9ff82e0 rsi              21 rdx               0 rcx               0
rax    7fffc9ff82e0 rbx    7fffc9ff8050 r8               20 r9     7fffa402e3f0
rbp    7fffc9ff82c0 rsp    7fffc9ff7f38 eflags         0x10202	[ IF RF ]

  0x00007fffab178720 0x0000000000000001 000000000000000000 0x00007fffc9ff82d0
=>0x00007fffab16fceb 0x000000000000006c 0x00007fffeb1f2ad0 0x0000000000000009
  0x00000000012c2d58 0x0000000000000079 0x00007fffeb1f2c80 000000000000000000
  0x00007fffc9ff8268 0x00007fffc9ff82e0 0x00000000012c2d58 0x000000000000007a
  0x00000000012c2d58 0x00007fffc9ff83f0 0x00007fffeb1f2b00 0x00007fffa4017f80

0x00007ffff2e3a2a0 in QVariant::QVariant(QVariant const&) () from /usr/lib64/qt4/libQtCore.so.4
gdb>> bt
#0  0x00007ffff2e3a2a0 in QVariant::QVariant(QVariant const&) () from /usr/lib64/qt4/libQtCore.so.4
#1  0x00007fffab16fceb in Tomahawk::InfoSystem::SpotifyPlugin::chartTypes() () from /usr/lib64/libtomahawk_infoplugin_spotify.so
#2  0x00007fffab178af5 in Tomahawk::InfoSystem::SpotifyPlugin::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) () from /usr/lib64/libtomahawk_infoplugin_spotify.so
#3  0x00007ffff2e296d4 in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () from /usr/lib64/qt4/libQtCore.so.4
#4  0x00007ffff321a2c3 in QNetworkReplyImplPrivate::finished() () from /usr/lib64/qt4/libQtNetwork.so.4
#5  0x00007ffff32ae025 in QNetworkAccessHttpBackend::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) () from /usr/lib64/qt4/libQtNetwork.so.4
#6  0x00007ffff2e2e49b in QObject::event(QEvent*) () from /usr/lib64/qt4/libQtCore.so.4
#7  0x00007ffff3def59c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#8  0x00007ffff3df8296 in QApplication::notify(QObject*, QEvent*) () from /usr/lib64/qt4/libQtGui.so.4
#9  0x000000000043eb96 in TomahawkApp::notify (this=<optimized out>, receiver=<optimized out>, e=<optimized out>) at /tmp/portage/media-sound/tomahawk-0.8.4-r1/work/tomahawk-0.8.4/src/tomahawk/TomahawkApp.cpp:862
#10 0x00007ffff2e104db in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib64/qt4/libQtCore.so.4
#11 0x00007ffff2e14cd1 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib64/qt4/libQtCore.so.4
#12 0x00007ffff2e470ae in postEventSourceDispatch(_GSource*, int (*)(void*), void*) () from /usr/lib64/qt4/libQtCore.so.4
#13 0x00007fffec7891d7 in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
#14 0x00007fffec789460 in g_main_context_iterate.isra () from /usr/lib64/libglib-2.0.so.0
#15 0x00007fffec78950c in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#16 0x00007ffff2e474ae in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/qt4/libQtCore.so.4
#17 0x00007ffff2e0df11 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/qt4/libQtCore.so.4
#18 0x00007ffff2e0e285 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/qt4/libQtCore.so.4
#19 0x00007ffff2cd92f9 in QThread::exec() () from /usr/lib64/qt4/libQtCore.so.4
#20 0x00007ffff6d2c58f in Tomahawk::InfoSystem::InfoSystemWorkerThread::run() () from /usr/lib64/libtomahawk.so.0.8.4
#21 0x00007ffff2cdc2b8 in QThreadPrivate::start(void*) () from /usr/lib64/qt4/libQtCore.so.4
#22 0x00007ffff0a2b434 in start_thread (arg=0x7fffc9ff9700) at pthread_create.c:334
#23 0x00007fffef24551d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
gdb>> 

```

**Comment by muesli** [comment]
The spotify plugin is involved because we try to load the Spotify charts from our server here. The crash isn't fixed yet, but I've finally managed to migrate the service to our new server, so the crash shouldn't be triggered anymore.
