### ISSUE TITLE
Crash in TrackView::currentChanged

### ISSUE THREAD

**Issue by vrutkovs** [tomahawk-player/tomahawk#522]
Latest master (a439427ca54287ef60cecf3e95e18667afdf9115) built with [Flatpak manifest](https://github.com/vrutkovs/flatpak-tomahawk) crashes on startup:
```
Thread 1 (Thread 0x7fb0b1141780 (LWP 6)):
#0  TrackView::currentChanged (this=0x179c220, current=..., previous=...) at /run/build/tomahawk/src/libtomahawk/playlist/TrackView.cpp:387
#1  0x00007fb0ad0a06fb in QAbstractItemView::setSelectionModel(QItemSelectionModel*) () from /lib/libQt5Widgets.so.5
#2  0x00007fb0ad0e2a07 in QTreeView::setSelectionModel(QItemSelectionModel*) () from /lib/libQt5Widgets.so.5
#3  0x00007fb0ad09b445 in QAbstractItemView::setModel(QAbstractItemModel*) () from /lib/libQt5Widgets.so.5
#4  0x00007fb0ad0e27d4 in QTreeView::setModel(QAbstractItemModel*) () from /lib/libQt5Widgets.so.5
#5  0x00007fb0b04d340c in TrackView::setProxyModel (this=this@entry=0x179c220, model=model@entry=0x17c8f50) at /run/build/tomahawk/src/libtomahawk/playlist/TrackView.cpp:197
#6  0x00007fb0b04d37eb in TrackView::TrackView (this=0x179c220, parent=<optimized out>) at /run/build/tomahawk/src/libtomahawk/playlist/TrackView.cpp:113
#7  0x00007fb0b04a0213 in ContextView::ContextView (this=0x179be80, parent=<optimized out>, caption=...) at /run/build/tomahawk/src/libtomahawk/playlist/ContextView.cpp:48
#8  0x00007fb0b058b8da in PlaylistViewPage::PlaylistViewPage (this=0x17a4f20, parent=<optimized out>, extraHeader=0x0) at /run/build/tomahawk/src/libtomahawk/viewpages/PlaylistViewPage.cpp:39
#9  0x00007fb0b04bea66 in QueueView::QueueView (this=0x17a4f20, parent=<optimized out>) at /run/build/tomahawk/src/libtomahawk/playlist/QueueView.cpp:37
#10 0x00000000004ac2d7 in TomahawkWindow::TomahawkWindow (this=0x179b0d0, parent=<optimized out>) at /run/build/tomahawk/src/tomahawk/TomahawkWindow.cpp:119
#11 0x000000000043d150 in TomahawkApp::onInfoSystemReady (this=0x7ffea38603d0) at /run/build/tomahawk/src/tomahawk/TomahawkApp.cpp:644
#12 0x00000000004bed35 in TomahawkApp::qt_static_metacall (_o=0x7ffea38603d0, _c=<optimized out>, _id=<optimized out>, _a=<optimized out>) at /run/build/tomahawk/src/tomahawk/moc_TomahawkApp.cpp:160
#13 0x00007fb0aacbef21 in QMetaObject::activate(QObject*, int, int, void**) () from /lib/libQt5Core.so.5
#14 0x00007fb0b0397434 in Tomahawk::InfoSystem::InfoSystem::init (this=0x15584d0) at /run/build/tomahawk/src/libtomahawk/infosystem/InfoSystem.cpp:184
#15 0x00007fb0b05ed115 in Tomahawk::InfoSystem::InfoSystem::qt_static_metacall (_o=0x15584d0, _c=<optimized out>, _id=<optimized out>, _a=<optimized out>)
    at /run/build/tomahawk/src/libtomahawk/moc_InfoSystem.cpp:499
#16 0x00007fb0aacbfa11 in QObject::event(QEvent*) () from /lib/libQt5Core.so.5
#17 0x00007fb0ace6f7fc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib/libQt5Widgets.so.5
#18 0x00007fb0ace74986 in QApplication::notify(QObject*, QEvent*) () from /lib/libQt5Widgets.so.5
#19 0x000000000043dbcb in TomahawkApp::notify (this=<optimized out>, receiver=<optimized out>, e=<optimized out>) at /run/build/tomahawk/src/tomahawk/TomahawkApp.cpp:871
#20 0x00007fb0aac941f8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib/libQt5Core.so.5
#21 0x00007fb0aac95fda in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /lib/libQt5Core.so.5
#22 0x00007fb0aace6323 in ?? () from /lib/libQt5Core.so.5
#23 0x00007fb0a7042cd7 in g_main_context_dispatch () from /lib/libglib-2.0.so.0
#24 0x00007fb0a7042f08 in ?? () from /lib/libglib-2.0.so.0
#25 0x00007fb0a7042fac in g_main_context_iteration () from /lib/libglib-2.0.so.0
#26 0x00007fb0aace672f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/libQt5Core.so.5
#27 0x00007fb0aac924ca in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/libQt5Core.so.5
#28 0x00007fb0aac9a58d in QCoreApplication::exec() () from /lib/libQt5Core.so.5
#29 0x000000000042e901 in main (argc=2, argv=<optimized out>) at /run/build/tomahawk/src/tomahawk/main.cpp:218
```

[Full log](https://gist.github.com/vrutkovs/e9f18c3761119977110fbda404cc5249)

**Comment by theli-ua** [comment]
also having this :-/

**Comment by username31480** [comment]
Ditto.
I have master branch checked out...I'd be happy to run a bit of debugging...I've committed as much spare time as I can at the moment, but did not get a useful backtrace to compare to OP.
I'll be honest, I have not looked extensively...is there some documentation that I've not yet found which has crash report tips?

**Comment by muesli** [comment]
Fixed in master.
