### ISSUE TITLE
It crashes.

### ISSUE THREAD

**Issue by JulianLai** [tomahawk-player/tomahawk#634]
```
(gdb) thread apply all backtrace

Thread 18 (Thread 0x7fffacff9700 (LWP 15660)):
#0  0x00007ffff4ace5d0 in  () at /usr/lib/libQt5Core.so.5
#1  0x00007ffff4acf8b8 in  () at /usr/lib/libQt5Core.so.5
#2  0x00007ffff4acfdef in QRegExp::exactMatch(QString const&) const () at /usr/lib/libQt5Core.so.5
#3  0x00007ffff4b4c97b in  () at /usr/lib/libQt5Core.so.5
#4  0x00007ffff4b4dcd5 in  () at /usr/lib/libQt5Core.so.5
#5  0x00007ffff4b4dfe4 in QDirIterator::next() () at /usr/lib/libQt5Core.so.5
#6  0x00007ffff4b486e8 in QDir::entryList(QStringList const&, QFlags<QDir::Filter>, QFlags<QDir::SortFlag>) const () at /usr/lib/libQt5Core.so.5
#7  0x00007ffff704dd07 in Tomahawk::Utils::PluginLoader::pluginPaths(QString const&) const ()
    at /usr/lib/libtomahawk.so.0.8.4
#8  0x00007ffff704ee79 in Tomahawk::Utils::PluginLoader::loadPlugins() const ()
    at /usr/lib/libtomahawk.so.0.8.4
#9  0x00007ffff6fbf248 in Tomahawk::InfoSystem::InfoSystemWorker::loadInfoPlugins() ()
    at /usr/lib/libtomahawk.so.0.8.4
#10 0x00007ffff6fbf884 in Tomahawk::InfoSystem::InfoSystemWorker::init(Tomahawk::InfoSystem::InfoSystemCache*) () at /usr/lib/libtomahawk.so.0.8.4
#11 0x00007ffff7201cbc in  () at /usr/lib/libtomahawk.so.0.8.4
#12 0x00007ffff4c6b1b2 in QObject::event(QEvent*) () at /usr/lib/libQt5Core.so.5
#13 0x00007ffff5be0e2c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /usr/lib/libQt5Widgets.so.5
#14 0x00007ffff5be8906 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#15 0x000055555559ab8c in  ()
#16 0x00007ffff4c3abb0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
    at /usr/lib/libQt5Core.so.5
#17 0x00007ffff4c3d406 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
    at /usr/lib/libQt5Core.so.5
---Type <return> to continue, or q <return> to quit---
#18 0x00007ffff4c95a54 in  () at /usr/lib/libQt5Core.so.5
#19 0x00007fffec0dfa57 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#20 0x00007fffec0dfc88 in  () at /usr/lib/libglib-2.0.so.0
#21 0x00007fffec0dfd1c in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#22 0x00007ffff4c95041 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#23 0x00007ffff4c38fdb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#24 0x00007ffff4a523ee in QThread::exec() () at /usr/lib/libQt5Core.so.5
#25 0x00007ffff6fac329 in Tomahawk::InfoSystem::InfoSystemWorkerThread::run() ()
    at /usr/lib/libtomahawk.so.0.8.4
#26 0x00007ffff4a5713b in  () at /usr/lib/libQt5Core.so.5
#27 0x00007ffff218c08a in start_thread () at /usr/lib/libpthread.so.0
#28 0x00007ffff414c1bf in clone () at /usr/lib/libc.so.6

Thread 17 (Thread 0x7fffad7fa700 (LWP 15659)):
#0  0x00007ffff4141cbb in poll () at /usr/lib/libc.so.6
#1  0x00007fffec0dfc09 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007fffec0dfd1c in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff4c95041 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#4  0x00007ffff4c38fdb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#5  0x00007ffff4a523ee in QThread::exec() () at /usr/lib/libQt5Core.so.5
#6  0x00007ffff6fabb3b in Tomahawk::InfoSystem::InfoSystemCacheThread::run() ()
    at /usr/lib/libtomahawk.so.0.8.4
#7  0x00007ffff4a5713b in  () at /usr/lib/libQt5Core.so.5
#8  0x00007ffff218c08a in start_thread () at /usr/lib/libpthread.so.0
---Type <return> to continue, or q <return> to quit---
#9  0x00007ffff414c1bf in clone () at /usr/lib/libc.so.6

Thread 16 (Thread 0x7fffadffb700 (LWP 15658)):
#0  0x00007ffff219238d in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007ffff4a585cc in QWaitCondition::wait(QMutex*, unsigned long) () at /usr/lib/libQt5Core.so.5
#2  0x00007ffff6fa6b46 in Tomahawk::IdThreadWorker::run() () at /usr/lib/libtomahawk.so.0.8.4
#3  0x00007ffff4a5713b in  () at /usr/lib/libQt5Core.so.5
#4  0x00007ffff218c08a in start_thread () at /usr/lib/libpthread.so.0
#5  0x00007ffff414c1bf in clone () at /usr/lib/libc.so.6

Thread 15 (Thread 0x7fffae7fc700 (LWP 15657)):
#0  0x00007ffff4141cbb in poll () at /usr/lib/libc.so.6
#1  0x00007fffec0dfc09 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007fffec0dfd1c in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff4c95041 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#4  0x00007ffff4c38fdb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#5  0x00007ffff4a523ee in QThread::exec() () at /usr/lib/libQt5Core.so.5
#6  0x00007ffff6f455d7 in  () at /usr/lib/libtomahawk.so.0.8.4
#7  0x00007ffff4a5713b in  () at /usr/lib/libQt5Core.so.5
#8  0x00007ffff218c08a in start_thread () at /usr/lib/libpthread.so.0
#9  0x00007ffff414c1bf in clone () at /usr/lib/libc.so.6

Thread 14 (Thread 0x7fffaeffd700 (LWP 15656)):
#0  0x00007ffff4141cbb in poll () at /usr/lib/libc.so.6
#1  0x00007fffec0dfc09 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007fffec0dfd1c in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
---Type <return> to continue, or q <return> to quit---
#3  0x00007ffff4c95041 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#4  0x00007ffff4c38fdb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#5  0x00007ffff4a523ee in QThread::exec() () at /usr/lib/libQt5Core.so.5
#6  0x00007ffff6f455d7 in  () at /usr/lib/libtomahawk.so.0.8.4
#7  0x00007ffff4a5713b in  () at /usr/lib/libQt5Core.so.5
#8  0x00007ffff218c08a in start_thread () at /usr/lib/libpthread.so.0
#9  0x00007ffff414c1bf in clone () at /usr/lib/libc.so.6

Thread 13 (Thread 0x7fffaf7fe700 (LWP 15655)):
#0  0x00007ffff4141cbb in poll () at /usr/lib/libc.so.6
#1  0x00007fffec0dfc09 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007fffec0dfd1c in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff4c95041 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#4  0x00007ffff4c38fdb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#5  0x00007ffff4a523ee in QThread::exec() () at /usr/lib/libQt5Core.so.5
#6  0x00007ffff6f455d7 in  () at /usr/lib/libtomahawk.so.0.8.4
#7  0x00007ffff4a5713b in  () at /usr/lib/libQt5Core.so.5
#8  0x00007ffff218c08a in start_thread () at /usr/lib/libpthread.so.0
#9  0x00007ffff414c1bf in clone () at /usr/lib/libc.so.6

Thread 12 (Thread 0x7fffaffff700 (LWP 15654)):
#0  0x00007ffff4141cbb in poll () at /usr/lib/libc.so.6
#1  0x00007fffec0dfc09 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007fffec0dfd1c in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
---Type <return> to continue, or q <return> to quit---
#3  0x00007ffff4c95041 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#4  0x00007ffff4c38fdb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#5  0x00007ffff4a523ee in QThread::exec() () at /usr/lib/libQt5Core.so.5
#6  0x00007ffff6f455d7 in  () at /usr/lib/libtomahawk.so.0.8.4
#7  0x00007ffff4a5713b in  () at /usr/lib/libQt5Core.so.5
#8  0x00007ffff218c08a in start_thread () at /usr/lib/libpthread.so.0
#9  0x00007ffff414c1bf in clone () at /usr/lib/libc.so.6

Thread 11 (Thread 0x7fffbe57f700 (LWP 15653)):
#0  0x00007ffff4141cbb in poll () at /usr/lib/libc.so.6
#1  0x00007fffec0dfc09 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007fffec0dfd1c in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff4c95041 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#4  0x00007ffff4c38fdb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#5  0x00007ffff4a523ee in QThread::exec() () at /usr/lib/libQt5Core.so.5
#6  0x00007ffff6f455d7 in  () at /usr/lib/libtomahawk.so.0.8.4
#7  0x00007ffff4a5713b in  () at /usr/lib/libQt5Core.so.5
#8  0x00007ffff218c08a in start_thread () at /usr/lib/libpthread.so.0
#9  0x00007ffff414c1bf in clone () at /usr/lib/libc.so.6

Thread 8 (Thread 0x7fffbfafb700 (LWP 15650)):
#0  0x00007ffff4141cbb in poll () at /usr/lib/libc.so.6
#1  0x00007fffec0dfc09 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007fffec0dfd1c in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
---Type <return> to continue, or q <return> to quit---
#3  0x00007ffff4c95041 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#4  0x00007ffff4c38fdb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#5  0x00007ffff4a523ee in QThread::exec() () at /usr/lib/libQt5Core.so.5
#6  0x00007ffff4a5713b in  () at /usr/lib/libQt5Core.so.5
#7  0x00007ffff218c08a in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007ffff414c1bf in clone () at /usr/lib/libc.so.6

Thread 7 (Thread 0x7fffcb7fe700 (LWP 15649)):
#0  0x00007ffff4146bb9 in syscall () at /usr/lib/libc.so.6
#1  0x00007fffec124cba in g_cond_wait_until () at /usr/lib/libglib-2.0.so.0
#2  0x00007fffec0b4121 in  () at /usr/lib/libglib-2.0.so.0
#3  0x00007fffec107484 in  () at /usr/lib/libglib-2.0.so.0
#4  0x00007fffec106ae5 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff218c08a in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007ffff414c1bf in clone () at /usr/lib/libc.so.6

Thread 6 (Thread 0x7fffcbfff700 (LWP 15648)):
#0  0x00007ffff4141cbb in poll () at /usr/lib/libc.so.6
#1  0x00007fffec0dfc09 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007fffec0dffa2 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#3  0x00007fffe8023546 in  () at /usr/lib/libgio-2.0.so.0
#4  0x00007fffec106ae5 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff218c08a in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007ffff414c1bf in clone () at /usr/lib/libc.so.6

Thread 5 (Thread 0x7fffd0a95700 (LWP 15647)):
---Type <return> to continue, or q <return> to quit---
#0  0x00007ffff4141cbb in poll () at /usr/lib/libc.so.6
#1  0x00007fffec0dfc09 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007fffec0dfd1c in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007fffec0dfd61 in  () at /usr/lib/libglib-2.0.so.0
#4  0x00007fffec106ae5 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff218c08a in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007ffff414c1bf in clone () at /usr/lib/libc.so.6

Thread 4 (Thread 0x7fffd3180700 (LWP 15646)):
#0  0x00007ffff4141cbb in poll () at /usr/lib/libc.so.6
#1  0x00007fffec0dfc09 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007fffec0dfd1c in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff4c95064 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#4  0x00007ffff4c38fdb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#5  0x00007ffff4a523ee in QThread::exec() () at /usr/lib/libQt5Core.so.5
#6  0x00007ffff50b0376 in  () at /usr/lib/libQt5DBus.so.5
#7  0x00007ffff4a5713b in  () at /usr/lib/libQt5Core.so.5
#8  0x00007ffff218c08a in start_thread () at /usr/lib/libpthread.so.0
#9  0x00007ffff414c1bf in clone () at /usr/lib/libc.so.6

Thread 3 (Thread 0x7fffdc5ab700 (LWP 15645)):
#0  0x00007ffff4141cbb in poll () at /usr/lib/libc.so.6
#1  0x00007fffe2a5b8e0 in  () at /usr/lib/libxcb.so.1
#2  0x00007fffe2a5d679 in xcb_wait_for_event () at /usr/lib/libxcb.so.1
#3  0x00007fffdf14474a in  () at /usr/lib/libQt5XcbQpa.so.5
#4  0x00007ffff4a5713b in  () at /usr/lib/libQt5Core.so.5
---Type <return> to continue, or q <return> to quit---
#5  0x00007ffff218c08a in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007ffff414c1bf in clone () at /usr/lib/libc.so.6

Thread 2 (Thread 0x7fffe0299700 (LWP 15644)):
#0  0x00007ffff219238d in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007ffff46d748d in __gthread_cond_wait (__mutex=<optimized out>, __cond=<optimized out>)
    at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/x86_64-pc-linux-gnu/bits/gthr-default.h:864
#2  0x00007ffff46d748d in std::condition_variable::wait(std::unique_lock<std::mutex>&) (this=<optimized out>, __lock=...) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/condition_variable.cc:53
#3  0x00007ffff11ba3f7 in  () at /usr/lib/libQt5WebKit.so.5
#4  0x00007ffff11ba539 in  () at /usr/lib/libQt5WebKit.so.5
#5  0x00007ffff46dda6f in std::execute_native_thread_routine(void*) (__p=0x555555d4e3d0)
    at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:83
#6  0x00007ffff218c08a in start_thread () at /usr/lib/libpthread.so.0
#7  0x00007ffff414c1bf in clone () at /usr/lib/libc.so.6

Thread 1 (Thread 0x7ffff7f37880 (LWP 15640)):
#0  0x00007ffff70e7bd0 in TrackView::currentChanged(QModelIndex const&, QModelIndex const&) ()
    at /usr/lib/libtomahawk.so.0.8.4
#1  0x00007ffff5e378ab in QAbstractItemView::setSelectionModel(QItemSelectionModel*) ()
    at /usr/lib/libQt5Widgets.so.5
#2  0x00007ffff5e7d8d8 in QTreeView::setSelectionModel(QItemSelectionModel*) ()
    at /usr/lib/libQt5Widgets.so.5
#3  0x00007ffff5e32d35 in QAbstractItemView::setModel(QAbstractItemModel*) ()
    at /usr/lib/libQt5Widgets.so.5
#4  0x00007ffff5e7d6f1 in QTreeView::setModel(QAbstractItemModel*) () at /usr/lib/libQt5Widgets.so.5
#5  0x00007ffff70e76f5 in TrackView::setProxyModel(PlayableProxyModel*) ()
---Type <return> to continue, or q <return> to quit---
    at /usr/lib/libtomahawk.so.0.8.4
#6  0x00007ffff70e7a57 in TrackView::TrackView(QWidget*) () at /usr/lib/libtomahawk.so.0.8.4
#7  0x00007ffff70b08ff in ContextView::ContextView(QWidget*, QString const&) ()
    at /usr/lib/libtomahawk.so.0.8.4
#8  0x00007ffff719b659 in PlaylistViewPage::PlaylistViewPage(QWidget*, QWidget*) ()
    at /usr/lib/libtomahawk.so.0.8.4
#9  0x00007ffff70d1087 in QueueView::QueueView(QWidget*) () at /usr/lib/libtomahawk.so.0.8.4
#10 0x000055555560ed57 in  ()
#11 0x000055555559a0ec in  ()
#12 0x00005555556246b5 in  ()
#13 0x00007ffff4c6a766 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/libQt5Core.so.5
#14 0x00007ffff6fad0f0 in Tomahawk::InfoSystem::InfoSystem::init() () at /usr/lib/libtomahawk.so.0.8.4
#15 0x00007ffff7200625 in  () at /usr/lib/libtomahawk.so.0.8.4
#16 0x00007ffff4c6b1b2 in QObject::event(QEvent*) () at /usr/lib/libQt5Core.so.5
#17 0x00007ffff5be0e2c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /usr/lib/libQt5Widgets.so.5
#18 0x00007ffff5be8906 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#19 0x000055555559ab8c in  ()
#20 0x00007ffff4c3abb0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
    at /usr/lib/libQt5Core.so.5
#21 0x00007ffff4c3d406 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
    at /usr/lib/libQt5Core.so.5
#22 0x00007ffff4c95a54 in  () at /usr/lib/libQt5Core.so.5
#23 0x00007fffec0dfa57 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#24 0x00007fffec0dfc88 in  () at /usr/lib/libglib-2.0.so.0
#25 0x00007fffec0dfd1c in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#26 0x00007ffff4c95041 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
---Type <return> to continue, or q <return> to quit---
#27 0x00007ffff4c38fdb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#28 0x00007ffff4c42028 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#29 0x000055555558b81a in  ()
#30 0x00007ffff4076f6a in __libc_start_main () at /usr/lib/libc.so.6
#31 0x000055555558dbda in _start ()
```

**Comment by ivanruvalcaba** [comment]
Nice day!

This sounds weird. Yesterday I built the PKGBUILD and Tomahawk run flawlessly. Here the code:

```sh
# Maintainer: Evgeniy Alekseev <arcanis at archlinux dot org>
# Contributor: Kuba Serafinowski <zizzfizzix at gmail dot com>

pkgname=tomahawk-qt5
_pkgname=tomahawk
pkgver=0.8.4
pkgrel=4
pkgdesc="A Music Player App written in C++/Qt5"
arch=('i686' 'x86_64')
url='https://tomahawk-player.org/'
license=('GPL3')
depends=('attica-qt5' 'gnutls' 'libechonest-qt5' 'liblastfm-qt5' 'lucene++'
         'phonon-qt5' 'qca-qt5' 'qt5-svg' 'qt5-webkit' 'qtkeychain-qt5' 'quazip-qt5'
         'taglib>=1.10')
makedepends=('boost' 'cmake' 'sparsehash' 'qt5-tools')
optdepends=('telepathy-qt5: integration with Telepathy')
provides=('tomahawk')
conflicts=('tomahawk')
install="${_pkgname}.install"
source=("http://download.tomahawk-player.org/${_pkgname}-${pkgver}.tar.bz2"
        "arch-build.patch")
sha512sums=('5b312f593eac39d06de05e24d4ce429122d0777a9d52d6db8c65309ac283d7ae560c2fc189b186f0f8b1a7bbe1135ed0d59e1d850de6a93655e53efe4f5317c7'
            '305c355fa583a5420df5523f9fad0334e7feb7ed814ba277dc42d9e20edb3837304f1755f252ddf6fa2bb09d204fccaffc5e8c03e3f76faaf51359a8a40a499b')

prepare() {
  rm -rf "build"
  mkdir "build"

  patch -p0 -i "arch-build.patch"
  sed -i '373iif ( !m_model ) return;' tomahawk-0.8.4/src/libtomahawk/playlist/TrackView.cpp
}

build() {
  cd "build"
  cmake -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DCMAKE_INSTALL_LIBEXECDIR="lib/${pkgname}" \
        -DCMAKE_BUILD_TYPE=Release \
        -DBUILD_WITH_QT4=OFF \
        -DBUILD_HATCHET=OFF \
        -DTAGLIB_MIN_VERSION=1.10 \
        -Wno-dev \
        "../${_pkgname}-${pkgver}"
  make
}

package() {
  cd "build"
  make DESTDIR="${pkgdir}" install
}
```

Take a look on this:

```sh
sed -i '373iif ( !m_model ) return;' tomahawk-0.8.4/src/libtomahawk/playlist/TrackView.cpp
```
 
I hope be helpful.

Best regards.
